future: true
permalink: /:title/
url: http://wenlxie.github.io
name: wenlxie.github.io
author: wenlxie
qq: 
email: xwlpt@126.com
github: wenlxie
paginate: 20
highlighter: rouge
truncate: true
about: "wenlxie"
