future: true
permalink: /:title/
url: http://wenlxie.github.io
name: c
author: wenlxie
qq: 
email: xwlpt@126.com
duoshuo: wenlxie
beian: 
cnzz: 
weibo: wenlxie
github: wenlxie
paginate: 20
highlighter: rouge
truncate: true
about: "YY哥(wenlxie)"
